version: "3.9"
   
services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8001:8000"
    volumes:
      - ./client:/app
