version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data/
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    # entrypoint: /docker_entrypoint.sh
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    working_dir: /app
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./client:/app

volumes:
  db_data:
